CREATE TABLE keepcoding.ivr_detail (
    calls_ivr_id INT,
    calls_phone_number VARCHAR(20),
    calls_ivr_result VARCHAR(50),
    calls_vdn_label VARCHAR(50),
    calls_start_date TIMESTAMP,
    calls_start_date_id INT GENERATED ALWAYS AS (CAST(TO_CHAR(calls_start_date, 'YYYYMMDD') AS INT)),
    calls_end_date TIMESTAMP,
    calls_end_date_id INT GENERATED ALWAYS AS (CAST(TO_CHAR(calls_end_date, 'YYYYMMDD') AS INT)),
    calls_total_duration INT,
    calls_customer_segment VARCHAR(50),
    calls_ivr_language VARCHAR(20),
    calls_steps_module VARCHAR(50),
    calls_module_aggregation VARCHAR(50),
    module_sequence INT,
    module_name VARCHAR(50),
    module_duration INT,
    module_result VARCHAR(50),
    step_sequence INT,
    step_name VARCHAR(50),
    step_result VARCHAR(50),
    step_description_error VARCHAR(255),
    document_type VARCHAR(20),
    document_identification VARCHAR(50),
    customer_phone VARCHAR(20),
    billing_account_id VARCHAR(50),
    PRIMARY KEY (calls_ivr_id, module_sequence, step_sequence)
);
